- key: APPINSIGHTS_CONNECTIONSTRING
  value: "{{servicename}}-APPINSIGHTS-CONNECTIONSTRING"
  type: "keyvault"
- key: AZURE_AISEARCH_ENDPOINT
  value: "{{servicename}}-AZURE-AISEARCH-ENDPOINT"
  type: "keyvault"
- key: AZURE_AISEARCH_KEY
  value: "{{servicename}}-AZURE-AISEARCH-KEY"
  type: "keyvault"
- key: AZURE_SEARCH_INDEX_NAME
  value: "{{servicename}}-AZURE-SEARCH-INDEX-NAME"
  type: "keyvault"
- key: AZURE_AISEARCH_SUMMARIES_KEY
  value: "{{servicename}}-AZURE-AISEARCH-SUMMARIES-KEY"
  type: "keyvault"
- key: AZURE_SEARCH_SUMMARIES_INDEX_NAME
  value: "{{servicename}}-AZURE-SEARCH-SUMMARIES-INDEX-NAME"
  type: "keyvault"
- key: AZURE_OPENAI_API_INSTANCE_NAME
  value: "{{servicename}}-AZURE-OPENAI-API-INSTANCE-NAME"
  type: "keyvault"
- key: AZURE_OPENAI_API_KEY
  value: "{{servicename}}-AZURE-OPENAI-API-KEY"
  type: "keyvault"
- key: BLOB_STORAGE_CONNECTION_STRING
  value: "{{servicename}}-BLOB-STORAGE-CONNECTION-STRING"
  type: "keyvault"
- key: BLOB_STORAGE_CONTAINER
  value: "{{servicename}}-BLOB-STORAGE-CONTAINER"
  type: "keyvault"
